### PR TITLE
Finished test case Tc112

### PR DESCRIPTION
**Pull request by sendulhuseyin**
added this code here
made small changes

### CODE REVIEW

**Review by gozelihsan — COMMENTED** [review]
what a great code!

**Review by gozelihsan — COMMENTED** [review]
great

**Review by gozelihsan — COMMENTED** [review]
so good

**Review by gozelihsan — COMMENTED** [review]
good

**Comment by klevismuda** [comment]
Perfect work

**Review by kgasimov — APPROVED** [review]
Good job!

**Pull request merged**
